### ISSUE TITLE
peppy on pypi

### ISSUE THREAD

**Issue by nsheff** [robmcmullen/peppy#888]
Hi @robmcmullen,

With `peppy` no longer being maintained, is there any chance you'd be willing to give up the name `peppy` in the pypi index for a new project I'm working on for a python module that reads my idea of PEP objects (so pep-py or peppy would be perfect for me)? You can see more about the project here:

Project home page: http://pepkit.github.io
Python module (which I would love to call `peppy`): https://github.com/pepkit/pep

**Comment by robmcmullen** [comment]
Sure, no problem. I don't know how to give up a name on pypi, though, and I don't know how complicated it is. My "fee" would be for you to research how to do that, boil it down to its essentials, and send a step-by-step procedure to me, and then I'll do it.

**Comment by nsheff** [comment]
Thanks! I will look into how this works and get back to you.

**Comment by nsheff** [comment]
Alright, it's fairly simple; if you go to this page:

https://pypi.python.org/pypi?:action=role_form&package_name=peppy

You should be able to add me as an Owner (my pypi username is also `nsheff`). 

That's all you need to do. That will allow me to clear out the current releases and upload my own, and remove you as the owner as well (I believe). Thanks, I appreciate it!

**Comment by robmcmullen** [comment]
OK, updated that on pypi so give it a shot.

**Comment by nsheff** [comment]
That worked great. Thank you for your help!
